### ISSUE TITLE
Path parameters are not updated

### ISSUE THREAD

**Issue by lepicekmichal** [strmbx/retroxios#1]
Can you please fix following behaviour?
https://codesandbox.io/s/spring-haze-87zc6?file=/src/index.ts

If you open console in attached codesandbox, then you can see that I am calling url with **AAAA path** and next time same url with **BBBB path**. But interceptor is not lying and is showing that I am the second time also calling **AAAA**, which is wrong.

**Comment by lepicekmichal** [comment]
This deserves immediate release of new version, since it's making library practically unusable

**Comment by tnychn** [comment]
I've already bumped the version and published it on NPM 5 days ago but seems I forgot to git push the `v0.4.0` tag. Thanks for reminding me though!
