### ISSUE TITLE
Added interceptor is global

### ISSUE THREAD

**Issue by lepicekmichal** [strmbx/retroxios#2]
I have added interceptor above **one** endpoint, but it has been invoked upon calling all the other endpoints too.

**Comment by tnychn** [comment]
After some investigations, it seems that `axios`'s interceptors mechanism does not allow each request call to have its own interceptor, instead it only allows setting global interceptors on the `AxiosInstance` object which will apply to every request call.

One possible solution is to make a clone of the `AxiosInstance` object and apply the per request interceptors on it for every request call.

For now, if you really want to set a per request interceptor, you can use a global interceptor that checks the request URL to determine whether or not to execute the interception:
```typescript
retroxios.interceptors.use((config) => {
  if (config.url === "my/target/request/path") {
    console.log("interception");
  }
  return config;
});
```

**Comment by lepicekmichal** [comment]
No worries, just remove per request interceptor from code and documentation and we can forget about it (for now)
